name: Build CEF 4896 for Windows x86

on: [workflow_dispatch]

env:
  GN_DEFINES: is_official_build=true use_thin_lto=false proprietary_codecs=true ffmpeg_branding=Chrome
  CEF_ARCHIVE_FORMAT: tar.bz2
  GYP_MSVS_VERSION: 2019

jobs:
  cef-windows-x86:
    runs-on: [self-hosted, Windows, X64]
    timeout-minutes: 720
    steps:
      - shell: cmd
        run: |
          curl https://bitbucket.org/chromiumembedded/cef/raw/master/tools/automate/automate-git.py -o automate-git.py
          python automate-git.py \
            --download-dir=C:\cef \
            --force-clean \
            --branch=4896 \
            --minimal-distrib \
            --client-distrib \
            --no-debug-build \
            --with-pgo-profiles
          python C:\s3cmd-2.3.0\s3cmd sync C:\cef\chromium\src\cef\binary_distrib\ --exclude "*" --include "*.tar.bz2" s3://cef-builds/4896/
