name: Build CEF

on: [push]

env:
  GN_DEFINES: is_official_build=true
  CEF_ARCHIVE_FORMAT: tar.bz2

jobs:
  cef-macos:
    runs-on: [self-hosted, macOS, X64]
    steps:
      - run: wget https://bitbucket.org/chromiumembedded/cef/raw/master/tools/automate/automate-git.py
      - run: python3 automate-git.py --download-dir=~/cef-builds --branch=4896 --minimal-distrib --client-distrib --force-clean --x64-build --with-pgo-profiles