name: Build CEF for macOS x64

on: [workflow_dispatch]

env:
  GN_DEFINES: is_official_build=true use_thin_lto=false proprietary_codecs=true ffmpeg_branding=Chrome
  CEF_ARCHIVE_FORMAT: tar.bz2

jobs:
  cef-macos-x64:
    runs-on: [self-hosted, macOS, X64]
    steps:
      - run: |
          curl https://bitbucket.org/chromiumembedded/cef/raw/master/tools/automate/automate-git.py -o automate-git.py
          python3 automate-git.py --download-dir=cef-download --branch=4896 --minimal-distrib --client-distrib --force-clean --x64-build --with-pgo-profiles --no-debug-build
